### ISSUE TITLE
warning message

### ISSUE THREAD

**Issue by Cindy0805** [biofilos/ctdg_finder#1]
I got warning messages when I was running "all_blasts.py" and "hits_dictionary.py" :

"usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead"
I tried to ignore the warnings, simply because I don't know how to fix it. However when I ran the last script "ctdg_finder.py", it just deleted my entire directory.

Could you help me to fix this?
thanks!

**Comment by biofilos** [comment]
Those warnings can be safely ignored. These are warnings from the Pandas library when working with slices of dataframes.
Can you post the command line you used to run ctdg_finder.py? The script will delete the output directory only if incomplete results are found. I guess that if the output directory is set  to "." (the directory were the script resides) and incomplete results are found, it might remove that directory. I will include an assertion to prevent the user from setting the output directory to the directory where the script is found

**Comment by Cindy0805** [comment]
this was the command line that I used: python3 ctdg_finder.py --ref_seq mini/all_seqs.fa --name_family test --blast_samples 1000 --db mini
I have another question: how many (minimum)closely related species should I add for the analysis, does it work only with one genome?
thanks a lot for your help.

**Comment by biofilos** [comment]
If you don't specify an output directory (via `--out`), your results should not be deleted by ctdg_finder and it should not delete any important files. CTDGFinder will only remove files if an analysis (with the same name) was aborted before completion.
All the sequences that you pass via `--ref_seq` are going to be considered as part of the same gene family. In the command line you used, it looks like you are setting all the protein sequences in the sample database. The reference sequence file has to have only sequences you "know" are from the same gene family (for example, all the prolactin genes in mice, as in the file `sample_query/prolactins.fa`)

Depending on the question you want to ask, the number of species might change. For example, if the species are too far apart in the phylogeny, you might be able to observe long-range CTDG changes, and by using closely related species, you could get a closer look into rapidly evolving clusters.

The sample database (`mini`) has only three chromosomes from human, mouse and cow. In the `extras` directory I included a set of scripts and documentation for how to build your own databases for CTDGFinder. That to say that CTDGFinder will work with as many genomes as you include in the database, or with a subset of such genomes you can specify via `--sp` arguments

I hope this helps

**Comment by Cindy0805** [comment]
thanks for you responses and sorry for not replaying.
it did solve my problems, I was able to get results (using the provided example data set) in the end.

**Comment by biofilos** [comment]
Nice!
In included scripts to format ctdg databases from NCBI genbank files.
If you want to work with Ensembl, I am working on that pipeline too
cheers
