### ISSUE TITLE
hmmr version fails in all kind of ways

### ISSUE THREAD

**Issue by evolgenomology** [biofilos/ctdg_finder#2]
Hi!

I am trying to run the version using hmmr and PANTHER on a single genome. Unfortunately, the preprocessing guide is a bit hard to understand, for example it took me a while to understand that I need to get the panther hmm profiles and how to name the files. Now the `run_hmmer.sh` script ran until after finishing the hmmer PANTHER screen, but failed in the `parse_big_hmmer_strict.py` script where it is looking for a file called "pfam_filtered.txt" here `pfam_filtered = open("pfam_filtered.txt", "w"). What is this file supposed to be?

Cheers

Philipp

**Comment by biofilos** [comment]
the most up-to-date branch is located at https://github.com/biofilos/ctdg_finder/tree/v1.1
I included a sample "genome", which you can use to make sure that the files are generated correctly. More information can be found in the preprocessing manual on that branch
I will gladly help you with any problems you my encounter running CTDGFinder

Juan Felipe

**Comment by evolgenomology** [comment]
Thanks a lot Juan Felipe,

I'll try the new version at once.

Philipp

**Comment by biofilos** [comment]
Please tell me if your issue is resolved, so that I can either close this issue, or continue troubleshooting with you to solve it.

**Comment by evolgenomology** [comment]
I sure will. Just did not have the time to test yesterday. 

⁣Sent from BlueMail ​
