### ISSUE TITLE
AssertionError: Some of the HMMer database files with prefix pfam do not exist

### ISSUE THREAD

**Issue by TelfordLab** [biofilos/ctdg_finder#6]
Hi again!

I am still trying to run v1.1 on the prepared data screened against the Pfam database, as previously described. Testing with the zinc finger hmm you provide in your test data set I get the following:
```
python3 ~/bioProgs/ctdg_finder/ctdg_finder.py -p zf_C2H2_13  -d $PWD -c 8 -S 1000 -n test -s "XBO"
Traceback (most recent call last):
  File "/home/philipp/bioProgs/ctdg_finder/ctdg_finder.py", line 494, in <module>
   check_arguments(data)
 File "/home/philipp/bioProgs/ctdg_finder/ctdg_finder.py", line 43, in check_arguments
  assert hmmer_files == 5, "Some of the HMMer database files with prefix pfam do not exist".
```
These are the files in my `panther` subfolder:
panther.hmm  Pfam-A.hmm  Pfam-A.hmm.h3f  Pfam-A.hmm.h3i  Pfam-A.hmm.h3m  Pfam-A.hmm.h3p.

Would you mind pointing me to what is missing here please. 

Thanks a lot

Philipp

**Comment by biofilos** [comment]
From the preprocessing guidelines

> The gene family/orthologs source selected by the user (and properly formatted by using hmmpress) will be used as database, and a sequence file named seqs_hmmer.fa will be used as query. By default, the hmm file will be assumed to be stored as ctdg_db/panther/panther.hmm and ctdg_db/seqs_hmmer.fa where ctdg_db is the directory where all the annotation files are stored (chromosomes.csv, genes_parsed.csv, etc).
The hmm used as database has to be named panther.hmm
