### ISSUE TITLE
how to prepare the gff file?

### ISSUE THREAD

**Issue by kanglizhu** [biofilos/ctdg_finder#7]
Hello,
I have finished the preprocessing pipeline, now I want to run the ctdg_finder.py. According to your manual, i need to prepare the Gff file as you suggested using preprocessing.py in the extras folder. But I cannot find that script, is it being changed? how can i prepare the gff file?

**Comment by biofilos** [comment]
Hello. Thanks for your interest in CTDGFinder.
You are right, that script is missing. I also found some holes in the documentation. I hope you are not in a hurry. I will fix those issues and report back here when I am done. Hopefully it will take me only a few days.

Juan Felipe Ortiz

**Comment by kanglizhu** [comment]
Hello, Thank you for your reply. 

I have tried every script in the extracts, and then I found I can generate the gff file by the following command :
**python3  extras/csv2gff.py  sample_genomes/chromosomes.json  sample_genomes/genes_parsed.csv  sample_genomes/gene_families.json   output.folder**

And gene_families.json file comes from  sample_genome/hmmer/pfam.json.  Now i'm trying to generate this file, but i am not so familar with json format. can you provide me one if possible?

But I don't know whether this is right?

kangli

**Comment by kanglizhu** [comment]
Hello,
 I have finished my analysis using the method i described above, but i'm not sure whether it is right. 
I will  try again when you fix those issues. 

Kangli

**Comment by biofilos** [comment]
Sounds good. For now, make sure that the gff looks like this:
```
chr1   Annotation         chromosome       1  1000000  .       +       .       ID=chr19;bandwidth=155348.4809  
chr1   Annotation         gene        107103   117102  .       +       .       ID=gene1;families=family1,family2  
chr1   Annotation         gene        202103   203012  .       +       .       ID=gene1;families=family3
```

Basically, that the last column of chromosomes has the ID and bandwidth attributes, and the genes have ID and families columns, where the families are comma-separated.

If you want, run the pipeline with the sample files I included. I incuded part of the MHC cluster, so you should be able to get it in the output. If you have any questions, I will be working on this full time from now until I finish, so don't hesitate to ask

Juan Felipe

**Comment by kanglizhu** [comment]
Hello, 
Using the sample data, I generate the gff file using command "**python3 extras/csv2gff.py sample_genomes/chromosomes.json sample_genomes/genes_parsed.csv sample_genomes/gene_families.json output.folder**".

After this step, I can obtain two files "Homo_sapiens_genes.gff"  and "Homo_sapiens_chroms.txt".
The gff file looks like this:

![image](https://user-images.githubusercontent.com/54318276/110724406-ad372900-8250-11eb-912a-e9dec5060739.png)
Many of the families are "None", maybe because the gene_families.json file only has MHC_I and Ig_3 families.

The Homo_sapiens_chroms.txt file is:
chr19	58617616
chrY	       56887902

Then I run "**python3 ctdg_finder.py config_cohesin.json**". After this step, I can get two files "Homo_sapiens_clusters.gff"  and "Homo_sapiens_merged_clusters.gff".
Part of the Homo_sapiens_clusters.gff is:

![image](https://user-images.githubusercontent.com/54318276/110724855-7dd4ec00-8251-11eb-8118-e30406a35c98.png)


Part of the  Homo_sapiens_merged_clusters.gff is:
![image](https://user-images.githubusercontent.com/54318276/110725046-d73d1b00-8251-11eb-8921-11aac92d9bca.png)

I think these results may be right.

Kangli

**Comment by biofilos** [comment]
I think so. The file "Homo_sapiens_merged.gff" shows a few clusters, and the genes of each cluster are annotated.
I hope the annotation of those resulting gff is clear. If there are any doubts, let me know

Juan Felipe

**Comment by kanglizhu** [comment]
Thank you so much for your help. If  I meet other problems, I will let you know.

Kangli

**Comment by biofilos** [comment]
I updated the pipeline to make it easier to generate the gff and chromosome files. This version runs only one script, and generates all the files necessary, including the HMMer search

**Comment by kanglizhu** [comment]
Great! I will try to run the updated pipeline, thank you so much!
